### ISSUE TITLE
How to put our apk into the `update.zip`?

### ISSUE THREAD

**Issue by ender503** [rbx-rdm/documentation#8]
Hi @YSYoon 
We build our `update.zip` successful, but I don't know how to put our APK into the `update.zip`?
Which folder should I put my APK?

**Comment by YSYoon** [comment]
Hello @ender503 ,

In order to add custom APKs,

1. Unzip APK(s)
2. Copy library file(s) (.so) form inside the APK to `ntx_addon/system/lib`
3. Copy APK file(s) to `ntx_addon/system/app`
4. Open and edit `device/fsl/imx6/ntx_6sl.mk` , add the APK(s) and library file(s)
5. Open and edit `build_android_img.sh` ([link](https://github.com/rbx-rdm/pp1/blob/0e8978008d2f854cd3bd05e3dcd91abd06ae358a/build_android_img.sh#L310)) - add your APK name to the list of APKs to sign.

After all the steps have been completed, you should have your APK(s) inside the firmware.

**Comment by ender503** [comment]
Thanks @YSYoon 
I finally put the APK into the `update.zip`, and it works! 👍
